/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.go.aist.resec.elgamal;

public class Elgamal {
  public static void SystemInit(String param) {
    ElgamalJNI.SystemInit(param);
  }

}
